updated files included in profile front end
lmartin73/trackit pull request #6
Opened 2017-05-02 03:50 UTC by jhubbard2017

2017-05-02 04:35 UTC, jhubbard2017 commented on src/app/components/forms/commons/addresstypes.js
> +var address_types = ["Home", "Work", "Other"]
Add address and phone types into one file. Also, change to const

2017-05-02 04:38 UTC, jhubbard2017 commented on src/app/routes/profile/content/editprofile.js
> +import phone_types from '../../../components/forms/commons/phonetypes'
Will be a single file

2017-05-02 05:18 UTC, jhubbard2017 commented on src/app/routes/profile/index.js
> +import HtmlRender from '../../components/utils/HtmlRender'
Remove (Not needed)

2017-05-02 05:21 UTC, lmartin73 requested changes

2017-05-02 05:21 UTC, lmartin73 commented on src/app/components/forms/commons/addresstypes.js
> +var address_types = ["Home", "Work", "Other"]
consider consolidating constants into a single file

2017-05-02 05:21 UTC, lmartin73 commented on src/app/components/forms/commons/phonetypes.js
> +var phone_types = ["Home", "Mobile", "Work", "Other"]
consider consolidating constants into a single file

2017-05-02 05:21 UTC, lmartin73 commented on src/app/routes/profile/content/editprofile.js
> +import phone_types from '../../../components/forms/commons/phonetypes'
Consider using absolute paths.

2017-05-02 05:21 UTC, lmartin73 commented on src/app/routes/profile/content/editprofile.js
> +        if (this.refs.imageSelect.files.length == 1) {
No magic numbers. Consider using an enumeration or definition

2017-05-02 05:21 UTC, lmartin73 commented on src/app/routes/profile/content/editprofile.js
> +            reader.readAsDataURL(this.refs.imageSelect.files[0]);
We should set a maximum photo size.

2017-05-02 05:21 UTC, lmartin73 commented on src/app/routes/profile/content/editprofile.js
> +                                                            </select><i/>
What is the '<I/>' ?

2017-05-02 05:21 UTC, lmartin73 commented on src/app/routes/profile/content/editprofile.js
> +                                                                <input type="text" name="street1" ref="street1" placeholder="Street 1"/>
what is address 2 label?

2017-05-02 05:21 UTC, lmartin73 commented on src/app/routes/profile/content/editprofile.js
> +                                                            <input type="text" name="street2" ref="street2" placeholder="Street 2"/>
what is address2 label?

2017-05-02 05:21 UTC, lmartin73 commented on src/app/routes/profile/content/editprofile.js
> +                                                            <input type="text" name="state" ref="state" placeholder="State"/>
set a maximum string length for state or consider adding in a drop down select option

2017-05-02 05:21 UTC, lmartin73 commented on src/app/routes/profile/content/editprofile.js
> +                                                            <input type="text" name="zip" ref="zip" placeholder="Zip"/>
set max string length, and validation to make sure it's a number

2017-05-02 05:21 UTC, lmartin73 commented on src/app/routes/profile/content/editprofile.js
> +                                                <br/><p>Make sure all fields are complete before saving changes.</p><br/>
"All required fields must be completed before saving" consider using this?

2017-05-02 05:21 UTC, lmartin73 commented on src/app/routes/profile/content/profile.js
> +                                                        <h4 className="txt-color-white font-md">Jan 1, 2014</h4>
get the current date

2017-05-02 05:21 UTC, lmartin73 commented on src/app/routes/profile/content/profile.js
> +                                                    <ol className="carousel-indicators">
remove carousel and have a static profile cover picture

2017-05-02 05:21 UTC, lmartin73 commented on src/app/routes/profile/content/profile.js
> +                                                    <div className="col-sm-3 profile-pic">
what is the 'alt' property used for?

2017-05-02 05:21 UTC, lmartin73 commented on src/app/routes/profile/content/profile.js
> +                                                        <a href="" className="btn btn-default btn-xs"><i className="fa fa-envelope-o" /> Send Email</a>
should we be using redux for routing ?

2017-05-03 04:58 UTC, lmartin73 requested changes

2017-05-03 04:58 UTC, lmartin73 commented on src/app/components/forms/commons/address_phone_types.js
> +export const addressTypes = ["Home", "Work", "Other"]
perhaps we should name this file to something more general like profile definitions or something defines.

2017-05-03 04:58 UTC, lmartin73 commented on src/app/routes/profile/containers/editprofile.js
> +const ALERT_TIMEOUT = 6000  // 6 seconds
how did you come up with a 6 second timeout?

2017-05-03 04:58 UTC, lmartin73 commented on src/app/routes/profile/containers/editprofile.js
> +                store.dispatch(push('settings/profile'));
what action are you dispatching here?

2017-05-03 04:58 UTC, lmartin73 commented on src/app/routes/profile/containers/editprofile.js
> +            var file = this.refs.imageSelect.files[FILE_CONSTANTS.index];
perhaps we can come up with better names for the constant so that it's more intuitive.

2017-05-03 04:58 UTC, lmartin73 commented on src/app/routes/profile/containers/editprofile.js
> +                                                            <select name="phonetype" ref="phonetype" defaultValue={""}>
should the default value be the first option?

2017-05-03 04:58 UTC, lmartin73 commented on src/app/routes/profile/containers/profileContainer.js
> +        this.userInfo = {
we should check in test code.

2017-05-03 05:03 UTC, jhubbard2017 commented on src/app/routes/profile/containers/editprofile.js
> +const ALERT_TIMEOUT = 6000  // 6 seconds
This seemed like a reasonable time for the user to see the alert, and dismiss it on their own or allow it to dismiss itself. Resulted to 6 seconds after testing shorter and longer times

2017-05-03 05:04 UTC, jhubbard2017 commented on src/app/routes/profile/containers/editprofile.js
> +                store.dispatch(push('settings/profile'));
react-router-redux action. Pushing "settings/profile" to the history.

2017-05-03 05:07 UTC, jhubbard2017 commented on src/app/routes/profile/containers/editprofile.js
> +                                                            <select name="phonetype" ref="phonetype" defaultValue={""}>
I would think setting the properties first would be better if we were worried about which properties were set first. All in all, defaultValue will be set from the redux store, and won't necessarily make a difference its its the first property or last

2017-05-03 05:09 UTC, jhubbard2017 commented on src/app/components/forms/commons/address_phone_types.js
> +export const addressTypes = ["Home", "Work", "Other"]
Done

2017-05-03 05:13 UTC, jhubbard2017 commented on src/app/routes/profile/containers/editprofile.js
> +            var file = this.refs.imageSelect.files[FILE_CONSTANTS.index];
Done

2017-05-03 05:14 UTC, jhubbard2017 commented on src/app/routes/profile/containers/profileContainer.js
> +        this.userInfo = {
Noted

2017-05-03 05:35 UTC, lmartin73 approved these changes

2017-05-04 04:03 UTC, merged